nome = input('Digite o seu nome: ')
sobrenome = input('Digite o seu sobrenome: ')
e_mail = input('Digite o seu e-mail: ')
telefone = input('Digite o numero do seu telefone: ')
cargo = input('Digite o seu cargo: ')
numero_identificacao = input('Digite o códico de identificação: ')

print('O crchá de identificação é:')
print('-' * 40)
print(f'{sobrenome.upper()}, {nome}')
print(f'{cargo.capitalize()}')
print(f'Número de identificação: {numero_identificacao}\n')
print(f'{e_mail.lower()}')
print(f'{telefone}')
print('-' * 40)
